# Generated by Django 3.2.7 on 2021-09-22 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=255)),
                ('contract_type', models.CharField(choices=[('Temprory', 'Temprory'), ('Contract', 'Contract'), ('Fresher', 'Fresher'), ('Internship', 'Internship')], max_length=255)),
                ('job_schedule', models.CharField(choices=[('Morning Shift', 'Morning Shift'), ('Night Shift', 'Night shift')], max_length=255)),
                ('supplement_pay', models.CharField(choices=[('Commission pay', 'Commission pay'), ('Overtime pay', 'Overtime pay'), ('Shift allowance', 'Shift allowance'), ('Joining bonus', 'Joining bonus')], max_length=255)),
                ('benefits', models.CharField(choices=[('Cell phone reimbursement', 'Cell phone reimbursement'), ('Commuter assistance', 'Commuter assistance'), ('Flexible schedule', 'Flexible schedule')], max_length=255)),
                ('job_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('your_role_in_hiring_process', models.CharField(choices=[('Owner', 'Owner'), ('CEO', 'CEO'), ('Recruiter', 'Recuriter'), ('Talent Acquisition', 'Talent Acquisition'), ('Assistant or Officer Manager', 'Assistant or Officer Manager'), ('Hiring Manager', 'Hiring Manager'), ('Human Resource Generalist', 'Human Resource Generalist'), ('Other', 'Other')], max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_category', models.CharField(choices=[('Back End Developer', 'Back End Developer'), ('Front End Developer', 'Front End Developer'), ('iOS Developer', 'iOS Developer'), ('Machine Learning', 'Machine Learning')], max_length=255)),
                ('location_of_company', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('work_from_home', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Temporarily due to COVID-19', 'Temporarily due to COVID-19')], max_length=255)),
                ('post_language', models.CharField(max_length=255)),
                ('no_of_hiring', models.PositiveIntegerField()),
                ('always_hiring', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('education', models.CharField(choices=[('Secondary(10th Pass)', 'Secondary(10th Pass)'), ('Higher Secondary(12th Pass)', 'Higher Secondary(12th Pass)'), ('Diploma', 'Diploma'), ("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('Doctorate', 'Doctorate')], max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('qual_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobdetails')),
            ],
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='jobd_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobpost'),
        ),
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('your_name', models.CharField(max_length=255)),
                ('phone_no', models.PositiveIntegerField()),
                ('company_size', models.IntegerField()),
                ('where_here_about_us', models.CharField(max_length=255)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobpost')),
            ],
        ),
    ]
