# Generated by Django 3.2.7 on 2021-09-22 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='comp_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobpost'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
    ]
