# Generated by Django 3.2.7 on 2021-09-23 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210923_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ('-created_at',)},
        ),
    ]
