# Generated by Django 3.2.7 on 2021-10-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210930_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='conf_num',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
