# Generated by Django 3.2.7 on 2021-09-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210917_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_jobseeker',
            field=models.BooleanField(default=True),
        ),
    ]
