# Generated by Django 3.2.7 on 2021-09-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210918_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_employer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_jobseeker',
        ),
    ]
