# Generated by Django 3.2.7 on 2021-09-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210920_0530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
