# Generated by Django 3.2.7 on 2021-09-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('employer', 'employer'), ('jobseeker', 'jobseeker')], default='jobseeker', max_length=255),
        ),
    ]
